site_name: "Home Assistant Community Store"
site_description: "HACS Documentation"
site_short_name: "HACS"
site_favicon_location: "https://brands.home-assistant.io/hacs/icon.png"

github_branch: "experimental"
github_repository: "hacs/documentation"

twitter_username: "@HACSIntegration"

navigation:
  - name: Users
    path: /users
  - name: Publishers
    path: /publishers
  - name: FAQ
    path: /faq
  - name: Help
    path: /help
  - name: Search
    icon: "M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z"
    path: /search

footer:
  - title: GitHub
    url: "/github"
  - title: Twitter
    url: "/twitter"
  - title: Discord
    url: "/discord"
  - title: Code of Conduct
    url: "https://github.com/hacs/.github/blob/master/CODE_OF_CONDUCT.md"
  - title: "Contact (no support!)"
    url: "mailto:hi@hacs.xyz"
